mybatis-plus:
  type-aliases-package: com.zql.mp.entity
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.92.8:3306/mybatis?characterEncoding=utf8&useSSL=false
    username: root
    password: 521xwl54zql@MYSQL
